// src/app/contact/page.tsx
import { Metadata } from "next";
import SectionHeading from "@/components/ui/SectionHeading";
import ContactForm from "@/components/sections/ContactForm";

export const metadata: Metadata = {
  title: "Contact | Adrian Jenson",
  description:
    "Get in touch with Adrian Jenson — available for freelance projects, AI/SaaS product development, and technical collaborations.",
  openGraph: {
    title: "Contact | Adrian Jenson",
    description:
      "Get in touch — available for freelance projects, AI/SaaS development, and collaborations.",
    url: "https://adrianjenson.com/contact",
  },
};

const socialLinks = [
  {
    label: "Email",
    value: "jensonadrian@gmail.com",
    href: "mailto:jensonadrian@gmail.com",
    icon: (
      <svg
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
      >
        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
        <polyline points="22,6 12,13 2,6" />
      </svg>
    ),
  },
  {
    label: "GitHub",
    value: "github.com/gongalt",
    href: "https://github.com/gongalt",
    icon: (
      <svg
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="currentColor"
        aria-hidden="true"
      >
        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
      </svg>
    ),
  },
  {
    label: "LinkedIn",
    value: "linkedin.com/in/adrianjenson",
    href: "https://linkedin.com/in/adrianjenson",
    icon: (
      <svg
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="currentColor"
        aria-hidden="true"
      >
        <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
        <rect x="2" y="9" width="4" height="12" />
        <circle cx="4" cy="4" r="2" />
      </svg>
    ),
  },
];

export default function ContactPage() {
  return (
    <main className="max-w-5xl mx-auto px-6 pt-32 pb-24">

      {/* ── Header ── */}
      <section aria-labelledby="contact-heading" className="mb-16">
        <SectionHeading number="01" title="Get In Touch" />
        <p className="text-slate leading-relaxed max-w-xl">
          I&apos;m currently available for freelance projects and collaborations. Whether
          you have a specific project in mind, want to explore AI integrations, or just
          want to connect — send me a message and I&apos;ll get back to you within 24 hours.
        </p>
      </section>

      <div className="grid lg:grid-cols-3 gap-12 items-start">

        {/* ── Form (takes 2 cols) ── */}
        <div className="lg:col-span-2">
          <ContactForm />
        </div>

        {/* ── Sidebar ── */}
        <aside aria-label="Direct contact options" className="space-y-6">

          {/* Availability badge */}
          <div className="bg-navy-light rounded-lg p-6 border border-navy-lighter">
            <div className="flex items-center gap-2 mb-3">
              <span
                className="w-2.5 h-2.5 rounded-full bg-green-accent animate-pulse"
                aria-hidden="true"
              />
              <span className="font-mono text-green-accent text-sm">Available for Work</span>
            </div>
            <p className="text-slate text-sm leading-relaxed">
              Open to freelance projects, fixed-scope contracts, and interesting product
              collaborations. Typical response time: within 24 hours.
            </p>
          </div>

          {/* Direct contacts */}
          <div className="bg-navy-light rounded-lg p-6 border border-navy-lighter">
            <h2 className="text-slate-lightest font-semibold mb-5 text-sm tracking-wider uppercase font-mono">
              Direct Contact
            </h2>
            <ul className="space-y-4" aria-label="Contact links">
              {socialLinks.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    target={link.href.startsWith("mailto") ? undefined : "_blank"}
                    rel={link.href.startsWith("mailto") ? undefined : "noopener noreferrer"}
                    className="flex items-start gap-3 group"
                    aria-label={`${link.label}: ${link.value}`}
                  >
                    <span className="text-green-accent mt-0.5 shrink-0 group-hover:text-slate-lightest transition-colors duration-200">
                      {link.icon}
                    </span>
                    <span className="min-w-0">
                      <span className="block text-xs text-slate font-mono mb-0.5">
                        {link.label}
                      </span>
                      <span className="block text-slate-light text-sm group-hover:text-green-accent transition-colors duration-200 break-all">
                        {link.value}
                      </span>
                    </span>
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* What to expect */}
          <div className="bg-navy-light rounded-lg p-6 border border-navy-lighter">
            <h2 className="text-slate-lightest font-semibold mb-4 text-sm tracking-wider uppercase font-mono">
              What to Expect
            </h2>
            <ul className="space-y-3">
              {[
                "Response within 24 hours",
                "Free 30-min discovery call",
                "Clear scope & pricing upfront",
                "Weekly progress updates",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2.5 text-slate text-sm">
                  <span className="text-green-accent shrink-0 text-xs" aria-hidden="true">
                    ▹
                  </span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </aside>
      </div>
    </main>
  );
}

// src/app/components/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="contact-container">
      <div class="contact-content">
        <p class="contact-overline">04. What's Next?</p>
        <h1 class="contact-title">Get In Touch</h1>
        <p class="contact-description">
          Although I'm not currently looking for any new opportunities, my inbox is always open.
          Whether you have a question or just want to say hi, I'll try my best to get back to you!
        </p>
        <a href="mailto:{{ contactInfo.email }}" class="contact-btn">Say Hello</a>
      </div>
    </section>

    <footer class="footer">
      <div class="footer-content">
        <p class="footer-text">Designed & Built by Adrian Jenson</p>
        <div class="social-links">
          <a href="https://{{ contactInfo.github }}" target="_blank" rel="noopener noreferrer"
             class="social-link" title="GitHub">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 0C5.374 0 0 5.373 0 12 0 17.302 3.438 21.8 8.207 23.387c.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" fill="currentColor"/>
            </svg>
          </a>
          <a href="https://{{ contactInfo.linkedin }}" target="_blank" rel="noopener noreferrer"
             class="social-link" title="LinkedIn">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" fill="currentColor"/>
            </svg>
          </a>
          <a href="mailto:{{ contactInfo.email }}" class="social-link" title="Email">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M3 8L10.89 13.26c.64.4 1.47.4 2.11 0L21 8M5 19h14c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </a>
        </div>
      </div>
    </footer>
  `,
  styles: [`
    :host {
      --navy: #0a192f;
      --light-navy: #112240;
      --green: #64ffda;
      --slate: #8892b0;
      --light-slate: #a8b2d1;
      --lightest-slate: #ccd6f6;
      --white: #e6f1ff;
    }

    .contact-container {
      background: var(--navy);
      color: var(--white);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 100px 2rem;
      text-align: center;
    }

    .contact-content {
      max-width: 600px;
      width: 100%;

      .contact-overline {
        color: var(--green);
        font-family: 'Courier New', monospace;
        font-size: 1rem;
        margin-bottom: 1rem;
      }

      .contact-title {
        font-size: clamp(40px, 5vw, 60px);
        font-weight: 600;
        color: var(--lightest-slate);
        margin-bottom: 1.5rem;
        line-height: 1.1;
      }

      .contact-description {
        color: var(--slate);
        font-size: 1.2rem;
        line-height: 1.6;
        margin-bottom: 3rem;
        max-width: 540px;
        margin-left: auto;
        margin-right: auto;
      }

      .contact-btn {
        display: inline-block;
        padding: 1.25rem 1.75rem;
        border: 1px solid var(--green);
        border-radius: 4px;
        background: transparent;
        color: var(--green);
        text-decoration: none;
        font-size: 1rem;
        font-family: 'Courier New', monospace;
        transition: all 0.25s cubic-bezier(0.645, 0.045, 0.355, 1);

        &:hover {
          background: rgba(100, 255, 218, 0.1);
          transform: translate(-4px, -4px);
          box-shadow: 4px 4px 0 var(--green);
        }
      }
    }

    .footer {
      background: var(--navy);
      color: var(--slate);
      padding: 2rem 0;
      border-top: 1px solid var(--light-navy);
    }

    .footer-content {
      max-width: 1000px;
      margin: 0 auto;
      padding: 0 2rem;
      text-align: center;

      .footer-text {
        font-family: 'Courier New', monospace;
        font-size: 0.9rem;
        margin-bottom: 1.5rem;
      }

      .social-links {
        display: flex;
        justify-content: center;
        gap: 1.5rem;

        .social-link {
          color: var(--slate);
          transition: all 0.25s cubic-bezier(0.645, 0.045, 0.355, 1);
          padding: 0.5rem;
          border-radius: 4px;

          &:hover {
            color: var(--green);
            transform: translateY(-3px);
          }

          svg {
            width: 20px;
            height: 20px;
          }
        }
      }
    }

    @media (max-width: 768px) {
      .contact-container {
        padding: 80px 1rem;
      }

      .contact-content {
        .contact-title {
          font-size: clamp(30px, 8vw, 50px);
        }

        .contact-description {
          font-size: 1.1rem;
          margin-bottom: 2.5rem;
        }

        .contact-btn {
          padding: 1rem 1.5rem;
          font-size: 0.9rem;
        }
      }

      .footer-content {
        padding: 0 1rem;

        .social-links {
          gap: 1rem;
        }
      }
    }

    @media (max-width: 480px) {
      .contact-container {
        padding: 60px 1rem;
      }

      .contact-content {
        .contact-description {
          font-size: 1rem;
        }

        .contact-btn {
          width: 100%;
          max-width: 280px;
        }
      }

      .footer-content {
        .footer-text {
          font-size: 0.8rem;
        }

        .social-links {
          .social-link svg {
            width: 18px;
            height: 18px;
          }
        }
      }
    }

    @media (max-width: 360px) {
      .contact-content {
        .contact-btn {
          padding: 0.875rem 1.25rem;
          font-size: 0.85rem;
        }
      }
    }
  `]
})
export class ContactComponent {
  contactInfo = {
    email: 'jensonadrian@gmail.com',
    linkedin: 'linkedin.com/in/adrianjenson',
    github: 'github.com/gongalt',
    location: 'Mandaue, Philippines'
  };
}
<section class="contact-page">
  <div class="contact-header">
    <h1>Get in Touch</h1>
    <p>Feel free to reach out for collaborations or just a friendly hello</p>
  </div>

  <div class="contact-content">
    <div class="contact-info">
      <h2>Professional Profiles</h2>
      <div class="info-grid">
        <div class="info-item">
          <i class="fab fa-github"></i>
          <div class="info-details">
            <h3>GitHub</h3>
            <a href="https://{{ contactInfo.github }}" target="_blank">{{ contactInfo.github }}</a>
          </div>
        </div>
        <div class="info-item">
          <i class="fab fa-linkedin"></i>
          <div class="info-details">
            <h3>LinkedIn</h3>
            <a href="https://{{ contactInfo.linkedin }}" target="_blank">{{ contactInfo.linkedin }}</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Contact form temporarily disabled
    <div class="contact-form">
      <h2>Send Message</h2>
      <form [formGroup]="contactForm" (ngSubmit)="onSubmit()">
        <div class="form-group">
          <label for="name">Name</label>
          <input 
            type="text" 
            id="name" 
            formControlName="name"
            [ngClass]="{ 'invalid': submitted && f['name'].errors }"
          >
          <div class="error-message" *ngIf="submitted && f['name'].errors">
            Name is required
          </div>
        </div>

        <div class="form-group">
          <label for="email">Email</label>
          <input 
            type="email" 
            id="email" 
            formControlName="email"
            [ngClass]="{ 'invalid': submitted && f['email'].errors }"
          >
          <div class="error-message" *ngIf="submitted && f['email'].errors">
            <span *ngIf="f['email'].errors['required']">Email is required</span>
            <span *ngIf="f['email'].errors['email']">Please enter a valid email</span>
          </div>
        </div>

        <div class="form-group">
          <label for="subject">Subject</label>
          <input 
            type="text" 
            id="subject" 
            formControlName="subject"
            [ngClass]="{ 'invalid': submitted && f['subject'].errors }"
          >
          <div class="error-message" *ngIf="submitted && f['subject'].errors">
            Subject is required
          </div>
        </div>

        <div class="form-group">
          <label for="message">Message</label>
          <textarea 
            id="message" 
            formControlName="message"
            rows="5"
            [ngClass]="{ 'invalid': submitted && f['message'].errors }"
          ></textarea>
          <div class="error-message" *ngIf="submitted && f['message'].errors">
            <span *ngIf="f['message'].errors['required']">Message is required</span>
            <span *ngIf="f['message'].errors['minlength']">Message must be at least 10 characters</span>
          </div>
        </div>

        <button type="submit" class="submit-btn">Send Message</button>
      </form>
    </div>
    -->
  </div>
</section>
